### PR TITLE
Consolidate sidebar

### PR DESCRIPTION
**Pull request by garrett-eclipse**
To make it easier to remove sidebars with one line commenting I've moved the action from cleanup.php into sidebar.php.

This is to correct #307 

@JeremyEnglert Can you check this doesn't break things? Also I think I messed up with my fork and branches so it looks like alot more code than the changes I made for this ticket are part of this. Maybe we have to merge my other PR and I'll redo this? I'm no GitPro so would appreciate your advice.

Cheers

### CODE REVIEW

**Comment by JeremyEnglert** [comment]
I love this idea. 

And I think you're right, this PR got a little weird.

Github allows you to continue to push commits to a PR, even after you've made the PR. To avoid this, you can create separate branches, so the PR's don't clash. 

Do you want to take a stab at that? Essentially you would:

- Pull down the master branch
- Create a new branch based off master
- Make your sidebar changes
- Submit a PR of that branch into the master JWP branch

**Comment by garrett-eclipse** [comment]
Alright, I think I've got it this time. Third times the charm right ;)
I've reset the branch and reapplied the specific changes there.
Let me know if there's any issue.

**Comment by JeremyEnglert** [comment]
Woo! Thanks @garrett-eclipse!

**Comment by garrett-eclipse** [comment]
;) no problem thanks for the git pointers

**Pull request merged**
