### PR TITLE
i18n correction and completion

### PR DESCRIPTION
**Pull request by senlin**
Hi Jeremy,
Sorry for the earlier mistakes, this time I made a fresh clean fork.
This PR contains all the things that were still open, you indeed did quite a lot already, but there was still some stuff left to do ;)
Cheers,
Piet

### CODE REVIEW

**Comment by JeremyEnglert** [comment]
This is awesome! I'll be merging this shortly!

**Comment by senlin** [comment]
Cool, glad you like it :)

**Comment by JeremyEnglert** [comment]
Closing this as all changes are in the other PR as well. :+1:

**Comment by senlin** [comment]
sorry, I made such a mess of it, I'm starting over

**Pull request closed without merging**
