### PR TITLE
Fixes #300 by segregating source from destination

### LINKED ISSUE #300: Imagemin Infinite Loop
If I remove an image from the /assets/images/ directory while `gulp watch` is running then the imagemin task gets stuck in an infinite loop. Wondering if there just needs to be a separate raw/distro directory for images? I know that creates some duplication but not sure what else is going on with that task. My best guess is the task is modifying the directory, it's also watching the directory for changes, so then it gets stuck: watching, modifying, watching, etc...

### PR DESCRIPTION
**Pull request by garrett-eclipse**
This fix avoids the infinite loop of imagemin when watching

### CODE REVIEW

**Comment by JeremyEnglert** [comment]
This PR really got me thinking about the file structure.

We have three directories where the bulk of the assets are:
- /assets/styles
- /assets/scripts
- /assets/images

The compiled/minified files are in those directories, while the working files are a directory deeper. This is consistent across these directories - which is great. But would it make more sense to have the compiled/minified files be the "deeper" files?

- /assets/styles (this holds the SCSS files)
- /assets/styles/css (this holds the minified files)
- /assets/scripts (this holds the individual script files)
- /assets/scripts/js (this holds the minified files)
- /assets/images (this holds the unminified files)
- /assets/images/minified (this holds the minified images)

@garrett-eclipse, I'd love your thoughts on this. z

**Comment by garrett-eclipse** [comment]
Thanks @JeremyEnglert imho I feel even more distinction would be beneficial this would make it easier to check in only the source and push to production without the source files.

I'm thinking something like;
/source/styles (this holds the SCSS files)
/assets/css (this holds the minified files)
/source/scripts (this holds the js partials)
/assets/js (this holds the minified files)
/source/images (this holds the original images)
/assets/img (this holds the optimized images)

Thinking with this structure your .gitignore can exclude the entire /assets directory. And if you have a deploy script you can have it exclude the entire source directory.

Just my two cents

**Comment by jackfearing** [comment]
This fix works for me however I was wondering if there was a way to setup a remove task which watches the src folder and if the image is not in the src folder then remove it from the optimized images folder?

**Comment by garrett-eclipse** [comment]
Thanks @jackfearing that's a good idea, can you spawn a unique ticket for that request so it can be accommodated properly. Cheers

**Comment by jackfearing** [comment]
Thanks Garrett -- just submitted a new ticket. [#360](https://github.com/JeremyEnglert/JointsWP/issues/306)

**Comment by garrett-eclipse** [comment]
Sorry I messed up my PRs by using my master. Closing this to cleanup and reopen via a branch.

**Comment by garrett-eclipse** [comment]
Created PR #312 to replace this. @JeremyEnglert I didn't find the gulp-improvements branch yet. When that's setup will you handle the further separation of directories as discussed in this PR?

**Pull request closed without merging**
