### PR TITLE
Map output

### PR DESCRIPTION
**Pull request by chuckn246**
gulp.task 'styles' will output regular and minified css and .map files. Delete line 44 if you don't want minified .map files.

### CODE REVIEW

**Comment by chuckn246** [comment]
Good God, I'll never get this right. Sorry, I meant to do it on the gulp updates branch..

**Comment by JeremyEnglert** [comment]
Very nice! I just want to make sure I'm understanding this correctly. 

Gulp can not produce two sourcemaps in a single stream. To overcome this, you used gulp-clone to create two separate streams/pipes (one for minified files, one for non-minified files). These are then merged into a single stream using gulp-merge. 

Does that sound about right?

**Comment by chuckn246** [comment]
- First part - Not sure, will continue messing with it
- Rest of the question, you got it

**Comment by JeremyEnglert** [comment]
I keep hitting an issue with this.

It creates maps for login.css, login.min.css and style.css - but doesn't create one for style.min.css. 

Trying to get that figured out.

**Comment by chuckn246** [comment]
If I recall I was having a similar issue with the map file and changing the order of the pipes fixed it. 

I'm pretty sure what I had output the style.min.css though but it's been a few days lol

**Comment by JeremyEnglert** [comment]
This is working great now. I actually manually merged it into the other branch. Huge thanks once again! 

I'm going to implement a similar output for the JS files.

**Comment by chuckn246** [comment]
Glad I could help!

**Comment by JeremyEnglert** [comment]
Ahhh. Now I found the hangup.

If you init the sourcemaps after Sass, the sourcemaps reference the CSS files instead of the Sass files. If you init the sourcemaps before Sass (as recommended), it doesn't compile the minified styles. Super weird. 

I think it may be a bug with cssnano.

**Pull request closed without merging**
