### PR TITLE
For parts/loop-archive-grid.php

### PR DESCRIPTION
**Pull request by senlin**
See the [archive grid page](http://jointswp.com/demo/category/grid/) on your demo site.

When the total number of posts is not dividable by 3, the last post float to the right.
This can be fixed by adding the end class to the last item, which then floats the last item to the left instead.

### CODE REVIEW

**Comment by JeremyEnglert** [comment]
Great idea! I'll be merging this as well - and adding to the CSS version.

**Comment by senlin** [comment]
Cool! I made a bit of a mess as I first thought I could do it with css, then later it turned out that that wouldn't work, so I did it using javascript instead. I tried making it less messy, by adding it to a branch, but for this to work properly I probably would have had to use a branch for the other changes too.
Sorry for that...

**Comment by JeremyEnglert** [comment]
I'll most likely close the other PR and merge this one - as this seems to include the grid fix and the translation fixes.

Again, huge thanks!

**Comment by senlin** [comment]
Yeah that should work too, glad I could help :)

**Comment by JeremyEnglert** [comment]
So something weird is happening in the byline. Which I don't understand, because the code looks fine. 

screen shot 2015-11-24 at 6 51 48 pm

**Comment by senlin** [comment]
That is strange indeed. Maybe try `sprintf` instead of `printf` although I'm not entirely sure. I usually do it like this without a problem...

**Comment by senlin** [comment]
Looked it up and it has to be

````
get_the_time( 'F j, Y' ),
get_the_author_posts_link(),
````

for the first two. Usually the categories list is done separately, but will work on it this afternoon to try and combine it.

**Comment by senlin** [comment]
ok got it, will be sending you a new PR for the byline only

**Comment by senlin** [comment]
sorry, I made such a mess of it, I'm starting over

**Pull request closed without merging**
