### PR TITLE
Added missing what-input.js to package.json

### PR DESCRIPTION
**Pull request by shoshorov**

### CODE REVIEW

**Comment by JeremyEnglert** [comment]
I believe this automatically gets pulled in with foundation-sites, doesn't it?

**Comment by shoshorov** [comment]
Actually in gulp.js the path to what-input.js is `'node_modules/what-input/dist/what-input.js'`, which is incorrect. In foundation-sites 3.1 npm package the path is `'node_modules/foundation-sites/node_modules/what-input/dist'`

**Comment by JeremyEnglert** [comment]
What version of Node are you using?

Newer versions of Node use a "flat" dependency hierarchy - so all packages end up directly in `/node_modules/` (instead of in sub-directories of other packages).

**Comment by shoshorov** [comment]
v4.4.7 on windows 10

**Comment by JeremyEnglert** [comment]
Bumped up recommended version to Node 6.x. Node 4.x will work, but the dependency structure is different.

**Pull request closed without merging**
