### PR TITLE
further i18n for jointswp

### PR DESCRIPTION
**Pull request by senlin**
Hi Jeremy,

Please find attached the almost complete internationalisation (i18n) of JointsWP.

For starters the textdomain you were using (jointstheme) was not correct as it needs to be the same as the theme slug. So I corrected that everywhere.

Then there were quite a few strings that still needed i18n. 

There were also strings that had some i18n, but needed to be corrected. A good example of that one is the [byline partial](https://github.com/senlin/JointsWP/blob/master/partials/content-byline.php).

The only thing that is still left is the comments output (lines 194-195 of my fork) in the [functions file](https://github.com/senlin/JointsWP/blob/master/functions.php#L187-L195). I wrote a comment on top of it, it's a bit complicated, so you need to figure that out on your own :)

Hope you like my work and you find it useful to learn more about internationalisation. Would be great if you can accept my pull request.

Cheers,
Piet

### CODE REVIEW

**Comment by JeremyEnglert** [comment]
This is awesome! However, it looks like this may have been done with an older version of Joints, which explains the conflicts. Have you checked out the newest version?

**Comment by senlin** [comment]
I thought I did, let me have a look...

**Comment by senlin** [comment]
Weird, it turned out that I already forked it a while back and re-forking doesn't really work, but I didn't realise that.

I deleted the previous fork, redone the work and will sent you a new PR soon

**Comment by senlin** [comment]
sorry, I made such a mess of it, I'm starting over

**Pull request closed without merging**
