### PR TITLE
Gallery

### PR DESCRIPTION
**Pull request by andycochran**
I've added F6 grid styles for WordPress's Gallery feature.

### CODE REVIEW

**Comment by JeremyEnglert** [comment]
This is awesome! Let me take it for a spin then I'll merge it.

Huge, huge, huge thanks!

**Comment by andycochran** [comment]
Cool. The only thing I was unsure about is manually setting the negative margins on `.gallery`. Surely there's a better way to align the left/right edges of content in nested grids with mixins.

**Comment by theodorocaliari** [comment]
Please merge this pull request... the gallery still not work property in site... (print: https://snag.gy/j2ukLv.jpg )

**Comment by JeremyEnglert** [comment]
@andycochran, do you think it would make sense to use includes from the Foundation grid for this? That way if changes are made to the grid, it also applies here.

http://foundation.zurb.com/sites/docs/grid.html#columns

Thoughts?

**Comment by andycochran** [comment]
Yup. This should be done in a way that works with responsive gutters. Let's wait for v6.3, then redo this PR.

**Comment by JeremyEnglert** [comment]
This has been added to JointsWP 5.0

**Pull request closed without merging**
